---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: changelog
  namespace: flux-system
spec:
  image: ghcr.io/ablestar/changelog
  interval: 1m0s
  secretRef:
    name: regcred
