---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: changelog
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: changelog
  filterTags:
    pattern: '^[a-zA-Z0-9-]+'
    policy:
      alphabetical:
        order: asc