apiVersion: apps/v1
kind: Deployment
metadata:
  name: changelog
  namespace: default
spec:
  selector:
    matchLabels:
      app: changelog
  template:
    metadata:
      labels:
        app: changelog
    spec:
      containers:
        - name: changelog
          image: ghcr.io/ablestar/changelog:staging-8f41234447b818183173ec8a2acefc2294360e3d-1671025960 # {"$imagepolicy": "flux-system:changelog"}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9898
              protocol: TCP
      imagePullSecrets:
        - name: regcred
